### ISSUE TITLE
怎么用啊

### ISSUE THREAD

**Issue by Xiao-yux** [Proviasw/nonebot-plugin-mcport#1]
![VM{R4A SKZ9RL(NH75Y(5HS](https://user-images.githubusercontent.com/79674967/218934227-8ee1a655-0e79-4aaa-a2a1-9d410a5a8d65.png)

**Comment by TissyBoxC** [comment]
请讲主人QQ的""删除，例如[114514,1919810]

**Comment by TissyBoxC** [comment]
> ![VM{R4A SKZ9RL(NH75Y(5HS](https://user-images.githubusercontent.com/79674967/218934227-8ee1a655-0e79-4aaa-a2a1-9d410a5a8d65.png)

有问题的话再reopen吧，我close了
