### ISSUE TITLE
关于前情提要i

### ISSUE THREAD

**Issue by kroazi** [Proviasw/nonebot-plugin-mcport#6]
async_mcrcon.py没找到 
site-packages目录没找到

**Comment by Clark-zy** [comment]
pip install async_mcrcon不可以吗

**Comment by TissyBoxC** [comment]
目前的新版本并不要求这个包

**Comment by TissyBoxC** [comment]
插件目录有个rcon文件夹,扔到site-packages里

**Comment by kroazi** [comment]
site-packages是什么

**Comment by kroazi** [comment]
> 插件目录有 rcon 文件夹, 扔到 site-packages 里

site-packages是什么

**Comment by TissyBoxC** [comment]
有虚拟环境就去找虚拟环境
没有就去电脑python安装目录

**Comment by kroazi** [comment]
> 有虚拟环境就访问虚拟环境 没有就去电脑python安装目录
我知道在哪了 那个是nonebot的bot目录
